dist: trusty
language: node_js
node_js:
- "8"
cache:
   directories:
   - node_modules
before_script:
- npm install -g httpserver
- npx run custom-build
- cd dist && httpserver -p 8080 &
script:
- npm cypress run
